//Mark Chen
//March 29 2019
//This program will help the robot navigate through a maze using functions that dictate movement and turning

#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1, lSensor, sensorLineFollower)
#pragma config(Sensor, in2, mSensor, sensorLineFollower)
#pragma config(Sensor, in3, rSensor, sensorLineFollower)
#pragma config(Sensor, in4, gyro, sensorGyro)
#pragma config(Sensor, in6, arm, sensorPotentiometer)
#pragma config(Sensor, dgtl1, rEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl3, lEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl6, touch, sensorTouch)
#pragma config(Sensor, dgtl8, sonar, sensorSONAR_cm)
#pragma config(Sensor, I2C_1, rightIME, sensorQuadEncoderOnI2CPort, , AutoAssign )
#pragma config(Sensor, I2C_2, leftIME, sensorQuadEncoderOnI2CPort, , AutoAssign )
#pragma config(Sensor, I2C_3, armIME, sensorQuadEncoderOnI2CPort, , AutoAssign )
#pragma config(Motor, port2, rMotor, tmotorVex393_MC29, openLoop, reversed, driveRight, encoderPort, I2C_1)
#pragma config(Motor, port3, lMotor, tmotorVex393_MC29, openLoop, driveLeft, encoderPort, I2C_2)
#pragma config(Motor, port6, armMotor, tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(DatalogSeries, 0, "LeftFollow", Sensors, Sensor, in1, 50)
#pragma config(DatalogSeries, 1, "MidFollow", Sensors, Sensor, in2, 50)
#pragma config(DatalogSeries, 2, "RightFollow", Sensors, Sensor, in3, 50)
//*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//

//This function will make the robot move straight forwards "int blocks" number of blocks on the grid of a table
void forwards(int blocks){
	motor[lMotor]= 127;
	motor[rMotor]= 127;
	wait1Msec(blocks*200/5.3*10);
}

//This function will make the robot turn 90 degrees to the left
void left(){
	motor[lMotor]= -127;
	motor[rMotor]= 127;
	wait1Msec(630);
}
//This function will make the robot turn 90 degrees to the right
void right(){
	motor[lMotor]= 127;
	motor[rMotor]= -127;
	wait1Msec(630);
}

//This function will move the arm up and out of the way
void armMove(){
	motor[armMotor] = -127;
	wait1Msec(100);
}

task main()
{
	//Rid of arm
	armMove();

	//Advance, turn, and keep moving in the maze until the end.

	forwards(11);		//Forwards 11 blocks
	left();					//Turn left
	forwards(4.5);	//Forwards 4.5 blocks
	left();					//Turn left
	forwards(11);		//Etc.
	right();
	forwards(4);
	right();
	forwards(16);
	right();
	forwards(8);
	left();
	forwards(4);
	left();
	forwards(9);
}
