#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1, lSensor, sensorLineFollower)
#pragma config(Sensor, in2, mSensor, sensorLineFollower)
#pragma config(Sensor, in3, rSensor, sensorLineFollower)
#pragma config(Sensor, in4, gyro, sensorGyro)
#pragma config(Sensor, in6, arm, sensorPotentiometer)
#pragma config(Sensor, dgtl1, rEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl3, lEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl6, touch, sensorTouch)
#pragma config(Sensor, dgtl8, sonar, sensorSONAR_cm)
#pragma config(Sensor, I2C_1, rightIME, sensorQuadEncoderOnI2CPort, , AutoAssign )
#pragma config(Sensor, I2C_2, leftIME, sensorQuadEncoderOnI2CPort, , AutoAssign )
#pragma config(Sensor, I2C_3, armIME, sensorQuadEncoderOnI2CPort, , AutoAssign )
#pragma config(Motor, port2, rMotor, tmotorVex393_MC29, openLoop, reversed, driveRight, encoderPort, I2C_1)
#pragma config(Motor, port3, lMotor, tmotorVex393_MC29, openLoop, driveLeft, encoderPort, I2C_2)
#pragma config(Motor, port6, armMotor, tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(DatalogSeries, 0, "LeftFollow", Sensors, Sensor, in1, 50)
#pragma config(DatalogSeries, 1, "MidFollow", Sensors, Sensor, in2, 50)
#pragma config(DatalogSeries, 2, "RightFollow", Sensors, Sensor, in3, 50)
//*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//

//Global variables for the return values of the left and right sensors
int senseL = 0;
int senseR = 0;

//This function will move the arm up and out of the way
void armMove(){
	motor[armMotor] = -127;
	wait1Msec(100);
}

task main()
{
	//Get rid of the arm to avoid potential obstuction with obstacles
	armMove();

	//Until the end, keep following the line
	while(true){
		//Update the values of the sensors
		senseL = SensorValue[lSensor];
		senseR = SensorValue[rSensor];

		//Check to see if the left side is darker than the right side
		if(senseL > senseR){
			//If the left side is darker than the right side, then move towards the left
			motor[rMotor] = 100;
			motor[lMotor] = 10;
		} else {
			//Otherwise, move towards the right
			motor[rMotor] = 10;
			motor[lMotor] = 100;
		}


	}
}
